baseURL: "https://mjvo.github.io/vms202d"
title: "VMS 202D"

defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: "yaml"

markup:
  goldmark:
    renderer:
      unsafe: true

theme: 
  - "hugo-course"

FootnoteReturnLinkContents: "â†©"

outputFormats:
  Remark:
    baseName: index
    mediaType: text/html
    isHTML: true
  
params:
  course:
    name: "Introduction to Visual Culture"
    dept_url: "https://aahvs.duke.edu"
    dept_logo: "images/AAHVS_Barcode_Logo.png"
    day_time: "Mondays & Wednesdays, 12:00 - 1:15 PM"
    location: "Auditorium, Nasher Museum of Art"
    discussion_sections:
      days_times:  "Fridays, 12:00 - 12:50 PM"
      location: "Section 1: A266 Smith Warehouse, Bay 10<br />Section 2: A290 Smith Warehouse, Bay 9"
    hero_img: "https://unsplash.com/photos/uKVs2ovR0KY/download?force=true&w=1920"
    hero_img_credit: 'Photo by <a href="https://unsplash.com/@olena2552?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">olena ivanova</a> on <a href="https://unsplash.com/?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>'